/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_presentacion.biblioteca;
import Capa_negocio.NegocioLibro;
import Capa_persistencia.Autor;
import Capa_persistencia.Libro;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pc
 */
public class MantenimientoLibro extends javax.swing.JFrame {
NegocioLibro negocio = new NegocioLibro();
    /**
     * Creates new form MantenimientoLibro
     */
    public MantenimientoLibro() {
    initComponents();
    setLocationRelativeTo(null);
    cargarComboAutores();
    cargarTabla();
}
private void limpiar() {
    txtIsbn.setText("");
    txtTitulo.setText("");
    txtValorPrestamo.setText("");

    if (cmbAutor.getItemCount() > 0) {
        cmbAutor.setSelectedIndex(0);
    }

    txtIsbn.requestFocus();
}

private void cargarComboAutores() {
    cmbAutor.removeAllItems();

    List<Autor> lista = negocio.listarAutores();

    if (lista != null) {
        for (Autor a : lista) {
            cmbAutor.addItem(a.getCodigo() + " - " + a.getNombre() + " " + a.getApellido());
        }
    }
}

private String obtenerCodigoAutorSeleccionado() {
    String texto = cmbAutor.getSelectedItem().toString();
    String codigo = texto.substring(0, texto.indexOf(" - "));
    return codigo;
}

private void seleccionarAutor(String codigo) {
    for (int i = 0; i < cmbAutor.getItemCount(); i++) {
        String item = cmbAutor.getItemAt(i).toString();

        if (item.startsWith(codigo + " - ")) {
            cmbAutor.setSelectedIndex(i);
            return;
        }
    }
}

private void cargarTabla() {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ISBN");
    modelo.addColumn("Título");
    modelo.addColumn("Autor");
    modelo.addColumn("Valor préstamo");

    List<Libro> lista = negocio.listar();

    if (lista != null) {
        for (Libro l : lista) {
            String autor = "";

            if (l.getCodAutor() != null) {
                autor = l.getCodAutor().getNombre() + " " + l.getCodAutor().getApellido();
            }

            modelo.addRow(new Object[]{
                l.getIsbn(),
                l.getTitulo(),
                autor,
                l.getValorPrestamo()
            });
        }
    }

    tblLibro.setModel(modelo);
}

private boolean validarCampos() {
    if (txtIsbn.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el ISBN");
        txtIsbn.requestFocus();
        return false;
    }

    if (txtTitulo.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el título del libro");
        txtTitulo.requestFocus();
        return false;
    }

    if (cmbAutor.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Primero debe registrar un autor");
        return false;
    }

    if (txtValorPrestamo.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el valor del préstamo");
        txtValorPrestamo.requestFocus();
        return false;
    }

    try {
        new BigDecimal(txtValorPrestamo.getText().trim());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "El valor del préstamo debe ser numérico");
        txtValorPrestamo.requestFocus();
        return false;
    }

    return true;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbAutor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtValorPrestamo = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Gestión de libros ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ISBN: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Titulo:");

        txtIsbn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Autor: ");

        cmbAutor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbAutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAutorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Valor del Prestamo:");

        txtValorPrestamo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtValorPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorPrestamoActionPerformed(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLibro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbAutor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValorPrestamo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTitulo)
                                    .addComponent(txtIsbn))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnInsertar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(cmbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(txtValorPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void cmbAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAutorActionPerformed

    private void txtValorPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorPrestamoActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
         if (!validarCampos()) {
        return;
    }

    String codAutor = obtenerCodigoAutorSeleccionado();

    int r = negocio.insertar(
            txtIsbn.getText().trim(),
            txtTitulo.getText().trim(),
            codAutor,
            new BigDecimal(txtValorPrestamo.getText().trim())
    );

    if (r == 1) {
        JOptionPane.showMessageDialog(this, "Libro insertado correctamente");
        cargarTabla();
        limpiar();
    } else {
        JOptionPane.showMessageDialog(this, "Error al insertar el libro");
    }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (!validarCampos()) {
        return;
    }

    String codAutor = obtenerCodigoAutorSeleccionado();

    int r = negocio.modificar(
            txtIsbn.getText().trim(),
            txtTitulo.getText().trim(),
            codAutor,
            new BigDecimal(txtValorPrestamo.getText().trim())
    );

    if (r == 1) {
        JOptionPane.showMessageDialog(this, "Libro modificado correctamente");
        cargarTabla();
        limpiar();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo modificar el libro");
    }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que desea eliminar este libro?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION
    );

    if (opcion == JOptionPane.YES_OPTION) {
        int r = negocio.eliminar(txtIsbn.getText().trim());

        if (r == 1) {
            JOptionPane.showMessageDialog(this, "Libro eliminado correctamente");
            cargarTabla();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el libro");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String isbn = JOptionPane.showInputDialog(this, "Ingrese el ISBN del libro:");

    if (isbn != null && !isbn.trim().isEmpty()) {
        Libro l = negocio.buscar(isbn.trim());

        if (l != null) {
            txtIsbn.setText(l.getIsbn());
            txtTitulo.setText(l.getTitulo());

            if (l.getValorPrestamo() != null) {
                txtValorPrestamo.setText(l.getValorPrestamo().toString());
            } else {
                txtValorPrestamo.setText("");
            }

            if (l.getCodAutor() != null) {
                seleccionarAutor(l.getCodAutor().getCodigo());
            }

        } else {
            JOptionPane.showMessageDialog(this, "No existe el libro");
        }
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tblLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibroMouseClicked
        // TODO add your handling code here:
        int fila = tblLibro.getSelectedRow();

    if (fila >= 0) {
        String isbn = tblLibro.getValueAt(fila, 0).toString();

        Libro l = negocio.buscar(isbn);

        if (l != null) {
            txtIsbn.setText(l.getIsbn());
            txtTitulo.setText(l.getTitulo());

            if (l.getValorPrestamo() != null) {
                txtValorPrestamo.setText(l.getValorPrestamo().toString());
            } else {
                txtValorPrestamo.setText("");
            }

            if (l.getCodAutor() != null) {
                seleccionarAutor(l.getCodAutor().getCodigo());
            }
        }
    }
    }//GEN-LAST:event_tblLibroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbAutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLibro;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtValorPrestamo;
    // End of variables declaration//GEN-END:variables
}
