/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_presentacion.mantenimiento;

/**
 *
 * @author pc
 */
public class MantenimientoActivo extends javax.swing.JFrame {

    boolean editar = false;
    Capa_negocio.NegocioActivo negocio = new Capa_negocio.NegocioActivo();

    /**
     * Creates new form MantenimientoActivo
     */
    public MantenimientoActivo() {
        initComponents();
        txtId.setEditable(false);
        txtId.setText(negocio.siguienteId());
        cargarTabla();

        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarActivo();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        tblActivo = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText(" Mantenimiento - Activo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 710, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Compra:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        txtId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 280, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 280, -1));

        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, -1));

        btnInsertar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        tblActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblActivoMouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblActivo.setViewportView(jTable2);

        getContentPane().add(tblActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 600, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTabla() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"ID", "Nombre", "Fecha Compra"}, 0);
        java.util.List<Capa_persistencia.ActivoMant> lista = negocio.listar();
        if (lista != null) {
            for (Capa_persistencia.ActivoMant a : lista) {
                String fecha = "";
                if (a.getFechaCompra() != null) {
                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                    fecha = sdf.format(a.getFechaCompra());
                }
                model.addRow(new Object[]{a.getCodigo(), a.getNombre(), fecha});
            }
        }
        jTable2.setModel(model);
    }

    private void limpiarCampos() {
        txtId.setText(negocio.siguienteId());
        txtNombre.setText("");
        txtFecha.setText("");
        editar = false;
    }

    private void seleccionarActivo() {
        editar = true;

        int fila = jTable2.getSelectedRow();

        if (fila >= 0) {
            String id = jTable2.getValueAt(fila, 0).toString();

            Capa_persistencia.ActivoMant a = negocio.buscar(id);

            if (a != null) {
                txtId.setText(a.getCodigo());
                txtNombre.setText(a.getNombre());

                if (a.getFechaCompra() != null) {
                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                    txtFecha.setText(sdf.format(a.getFechaCompra()));
                } else {
                    txtFecha.setText("");
                }
            }
        }
    }

    private java.util.Date parsearFecha(String texto) throws Exception {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        return sdf.parse(texto);
    }
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText().trim();
        String nombre = txtNombre.getText().trim();
        String fecha = txtFecha.getText().trim();
        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el nombre");
            return;
        }
        if (fecha.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese la fecha (dd/MM/yyyy)");
            return;
        }
        try {
            java.util.Date fechaDate = parsearFecha(fecha);
            int res = negocio.insertar(id, nombre, fechaDate);
            if (res == 1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Activo insertado correctamente");
                limpiarCampos();
                cargarTabla();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al insertar");
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use dd/MM/yyyy  Ejemplo: 15/03/2024");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (!editar) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla primero");
            return;
        }
        String id = txtId.getText().trim();
        String nombre = txtNombre.getText().trim();
        String fecha = txtFecha.getText().trim();
        if (nombre.isEmpty() || fecha.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }
        try {
            java.util.Date fechaDate = parsearFecha(fecha);
            int res = negocio.modificar(id, nombre, fechaDate);
            if (res == 1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Modificado correctamente");
                limpiarCampos();
                cargarTabla();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use dd/MM/yyyy");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
       if (!editar) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla primero");
        return;
    }

    String id = txtId.getText().trim();

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Eliminar el activo: " + txtNombre.getText() + "?",
            "Confirmar",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        int res = negocio.eliminar(id);

        if (res == 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Eliminado correctamente");
            limpiarCampos();
            cargarTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar. El activo está usado en mantenimientos.");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblActivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblActivoMouseClicked
        // TODO add your handling code here:
        seleccionarActivo();
    }//GEN-LAST:event_tblActivoMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String id = javax.swing.JOptionPane.showInputDialog(
                this,
                "Ingrese el código del activo a buscar:",
                "Buscar activo",
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (id == null) {
            return;
        }

        id = id.trim();

        if (id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un código");
            return;
        }

        Capa_persistencia.ActivoMant a = negocio.buscar(id);

        if (a != null) {
            txtId.setText(a.getCodigo());
            txtNombre.setText(a.getNombre());

            if (a.getFechaCompra() != null) {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                txtFecha.setText(sdf.format(a.getFechaCompra()));
            } else {
                txtFecha.setText("");
            }

            editar = true;

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Activo no encontrado");
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoActivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTable jTable2;
    private javax.swing.JScrollPane tblActivo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
