/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_presentacion.mantenimiento;

/**
 *
 * @author pc
 */
public class MantenimientoComplejo extends javax.swing.JFrame {

    Capa_negocio.NegocioMantenimiento negocio = new Capa_negocio.NegocioMantenimiento();
    java.util.List<Capa_persistencia.DetMantenimiento> detallesTemp = new java.util.ArrayList<>();
    boolean editar = false;

    /**
     * Creates new form MantenimientoComplejo
     */
    public MantenimientoComplejo() {
        initComponents();
        setLocationRelativeTo(null);
        txtNumero.setEditable(false);
        txtNumero.setText(negocio.siguienteNumero());

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        txtFecha.setText(sdf.format(new java.util.Date()));

        cargarCombos();
        cargarTablaCab();
        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
                new String[]{"ID", "Activo", "Actividad", "Valor"}, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void cargarCombos() {
        cmbActivo.removeAllItems();
        java.util.List<Capa_persistencia.ActivoMant> activos = negocio.listarActivos();
        if (activos != null) {
            for (Capa_persistencia.ActivoMant a : activos) {
                cmbActivo.addItem(a.getCodigo() + " - " + a.getNombre());
            }
        }
        cmbActividad.removeAllItems();
        java.util.List<Capa_persistencia.Actividad> actividades = negocio.listarActividades();
        if (actividades != null) {
            for (Capa_persistencia.Actividad a : actividades) {
                cmbActividad.addItem(a.getCodigo() + " - " + a.getNombre());
            }
        }
    }

    private void cargarTablaCab() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"Numero", "Fecha", "Responsable"}, 0);
        java.util.List<Capa_persistencia.CabMantenimiento> lista = negocio.listarCab();
        if (lista != null) {
            for (Capa_persistencia.CabMantenimiento c : lista) {
                String fecha = "";
                if (c.getFecha() != null) {
                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                    fecha = sdf.format(c.getFecha());
                }
                model.addRow(new Object[]{c.getNumero(), fecha, c.getResponsable()});
            }
        }
        tblDetalle1.setModel(model);
        tblDetalle1.revalidate();
        tblDetalle1.repaint();
    }

    private void cargarTablaDet(String numero) {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"ID", "Activo", "Actividad", "Valor"}, 0);
        java.util.List<Capa_persistencia.DetMantenimiento> lista = negocio.listarDet(numero);
        if (lista != null) {
            for (Capa_persistencia.DetMantenimiento d : lista) {
                model.addRow(new Object[]{
                    d.getIdDet(),
                    d.getCodActivo() != null ? d.getCodActivo().getNombre() : "",
                    d.getCodActividad() != null ? d.getCodActividad().getNombre() : "",
                    d.getValor()
                });
            }
        }
        tblDetalle.setModel(model);
    }

    private void cargarTablaDetTemp() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new String[]{"ID", "Activo", "Actividad", "Valor"}, 0);
        for (Capa_persistencia.DetMantenimiento d : detallesTemp) {
            model.addRow(new Object[]{
                d.getIdDet(),
                d.getCodActivo() != null ? d.getCodActivo().getNombre() : "",
                d.getCodActividad() != null ? d.getCodActividad().getNombre() : "",
                d.getValor()
            });
        }
        tblDetalle.setModel(model);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblCabecera = new javax.swing.JTable();
        txtNumero = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtResponsable = new javax.swing.JTextField();
        cmbActivo = new javax.swing.JComboBox<>();
        cmbActividad = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tblCabecera1 = new javax.swing.JScrollPane();
        tblDetalle1 = new javax.swing.JTable();

        tblCabecera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCabeceraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCabecera);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        txtResponsable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponsableActionPerformed(evt);
            }
        });

        cmbActivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActivoActionPerformed(evt);
            }
        });

        cmbActividad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActividadActionPerformed(evt);
            }
        });

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Agregar Detalle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDetalle);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Registro de mantenimiento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Número:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Fecha: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText(" Responsable:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText(" ──── DETALLE ────────────────────────────────────────── ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Activo: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Actividad:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText(" Valor: ");

        tblCabecera1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCabecera1MouseClicked(evt);
            }
        });

        tblDetalle1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetalle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalle1MouseClicked(evt);
            }
        });
        tblCabecera1.setViewportView(tblDetalle1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20)
                        .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(cmbActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel7)
                        .addGap(13, 13, 13)
                        .addComponent(cmbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel8)
                        .addGap(32, 32, 32)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(tblCabecera1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(cmbActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cmbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(19, 19, 19)
                .addComponent(jButton3)
                .addGap(9, 9, 9)
                .addComponent(jButton4)
                .addGap(39, 39, 39)
                .addComponent(tblCabecera1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void tblCabeceraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCabeceraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCabeceraMouseClicked

    private void tblDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDetalleMouseClicked

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsableActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void cmbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbActivoActionPerformed

    private void cmbActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbActividadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cmbActivo.getSelectedItem() == null || cmbActividad.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione activo y actividad");
            return;
        }
        String valorTxt = txtValor.getText().trim();
        if (valorTxt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el valor");
            return;
        }
        try {
            java.math.BigDecimal valor = new java.math.BigDecimal(valorTxt);
            String codActivo = cmbActivo.getSelectedItem().toString().split(" - ")[0];
            String codActividad = cmbActividad.getSelectedItem().toString().split(" - ")[0];
            Capa_persistencia.DetMantenimiento det = new Capa_persistencia.DetMantenimiento();
            det.setIdDet(negocio.siguienteIdDet().add(new java.math.BigDecimal(detallesTemp.size())));
            for (Capa_persistencia.ActivoMant a : negocio.listarActivos()) {
                if (a.getCodigo().equals(codActivo)) {
                    det.setCodActivo(a);
                    break;
                }
            }
            for (Capa_persistencia.Actividad a : negocio.listarActividades()) {
                if (a.getCodigo().equals(codActividad)) {
                    det.setCodActividad(a);
                    break;
                }
            }
            det.setValor(valor);
            detallesTemp.add(det);
            cargarTablaDetTemp();
            txtValor.setText("");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Valor inválido");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String numero = txtNumero.getText().trim();
        String fecha = txtFecha.getText().trim();
        String responsable = txtResponsable.getText().trim();
        if (fecha.isEmpty() || responsable.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete fecha y responsable");
            return;
        }
        if (detallesTemp.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Agregue al menos un detalle");
            return;
        }
        java.math.BigDecimal total = java.math.BigDecimal.ZERO;
        for (Capa_persistencia.DetMantenimiento d : detallesTemp) {
            total = total.add(d.getValor());
        }
        try {
            java.util.Date fechaDate = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(fecha);
            int res = negocio.insertarCabConIntegracion(numero, fechaDate, responsable,
                    detallesTemp, total);
            if (res == 1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Guardado y asiento contable generado");
                detallesTemp.clear();
                txtNumero.setText(negocio.siguienteNumero());
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                txtFecha.setText(sdf.format(new java.util.Date()));
                txtResponsable.setText("");
                txtValor.setText("");
                editar = false;
                cargarTablaCab();
                cargarTablaDetTemp();
            } else if (res == -2) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo guardar. Revise que existan las cuentas: Gasto Mantenimiento y Bancos");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (!editar) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla primero");
            return;
        }
        String numero = txtNumero.getText().trim();
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Eliminar mantenimiento " + numero + " y todos sus detalles?",
                "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            int res = negocio.eliminarCab(numero);
            if (res == 1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Eliminado correctamente");
                txtNumero.setText(negocio.siguienteNumero());
                txtFecha.setText("");
                txtResponsable.setText("");
                editar = false;
                cargarTablaCab();
                tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{}, new String[]{"ID", "Activo", "Actividad", "Valor"}));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txtNumero.setText(negocio.siguienteNumero());

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        txtFecha.setText(sdf.format(new java.util.Date()));

        txtResponsable.setText("");
        txtValor.setText("");
        detallesTemp.clear();
        cargarTablaDetTemp();
        editar = false;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblDetalle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalle1MouseClicked
        // TODO add your handling code here:
        int fila = tblDetalle1.getSelectedRow();
        if (fila >= 0) {
            txtNumero.setText(tblDetalle1.getValueAt(fila, 0).toString());
            txtFecha.setText(tblDetalle1.getValueAt(fila, 1).toString());
            txtResponsable.setText(tblDetalle1.getValueAt(fila, 2).toString());
            String numero = tblDetalle1.getValueAt(fila, 0).toString();
            cargarTablaDet(numero);
            editar = true;
        }
    }//GEN-LAST:event_tblDetalle1MouseClicked

    private void tblCabecera1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCabecera1MouseClicked
        // TODO add your handling code here

    }//GEN-LAST:event_tblCabecera1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoComplejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoComplejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoComplejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoComplejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoComplejo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbActividad;
    private javax.swing.JComboBox<String> cmbActivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCabecera;
    private javax.swing.JScrollPane tblCabecera1;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTable tblDetalle1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtResponsable;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
