/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_presentacion.menus;
import Capa_presentacion.CreateAccount;
/**
 *
 * @author pc
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
  
 private String usuarioActual;

    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        btnUsuarios.setVisible(false);
    }

    public Menu(String usuario) {
        initComponents();
        setLocationRelativeTo(null);

        this.usuarioActual = usuario;

        if ("admin".equalsIgnoreCase(usuarioActual)) {
            btnUsuarios.setVisible(true);
        } else {
            btnUsuarios.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mantenimiento_BTN = new javax.swing.JButton();
        Activos_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Biblioteca_BTN = new javax.swing.JButton();
        Contabilidad_BTN = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Mantenimiento_BTN.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Mantenimiento_BTN.setText("Mantenimiento");
        Mantenimiento_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mantenimiento_BTNActionPerformed(evt);
            }
        });

        Activos_BTN.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Activos_BTN.setText("Activos");
        Activos_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Activos_BTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Menu");

        Biblioteca_BTN.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Biblioteca_BTN.setText("Biblioteca");
        Biblioteca_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Biblioteca_BTNActionPerformed(evt);
            }
        });

        Contabilidad_BTN.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Contabilidad_BTN.setText("Contabilidad");
        Contabilidad_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contabilidad_BTNActionPerformed(evt);
            }
        });

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnUsuarios.setText("Administración de usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Mantenimiento_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(Activos_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Biblioteca_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Contabilidad_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 138, Short.MAX_VALUE)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(Mantenimiento_BTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Activos_BTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Biblioteca_BTN)
                .addGap(18, 18, 18)
                .addComponent(Contabilidad_BTN)
                .addGap(27, 27, 27)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Activos_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Activos_BTNActionPerformed
        // TODO add your handling code here:
        MenuActivos ventana = new MenuActivos();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

    }//GEN-LAST:event_Activos_BTNActionPerformed

    private void Mantenimiento_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mantenimiento_BTNActionPerformed
        // TODO add your handling code here:
        MenuMantenimiento ventana = new MenuMantenimiento();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

    }//GEN-LAST:event_Mantenimiento_BTNActionPerformed

    private void Contabilidad_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contabilidad_BTNActionPerformed
        // TODO add your handling code here:
        MenuContabilidad ventana = new MenuContabilidad();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_Contabilidad_BTNActionPerformed

    private void Biblioteca_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Biblioteca_BTNActionPerformed
        // TODO add your handling code here:
        MenuBiblioteca ventana = new MenuBiblioteca();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_Biblioteca_BTNActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
    CreateAccount ventana = new CreateAccount();
    ventana.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Activos_BTN;
    private javax.swing.JButton Biblioteca_BTN;
    private javax.swing.JButton Contabilidad_BTN;
    private javax.swing.JButton Mantenimiento_BTN;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
