/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_presentacion.activos;
import Capa_negocio.NegocioActivoDep;
import Capa_persistencia.Activo;
import Capa_persistencia.TipoActivo;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pc
 */
public class MantenimientoActivoDep extends javax.swing.JFrame {
NegocioActivoDep negocio = new NegocioActivoDep();
    /**
     * Creates new form MantenimientoActivoDep
     */
    public MantenimientoActivoDep() {
        initComponents();
    setLocationRelativeTo(null);
    txtId1.setEditable(false);
    cargarComboTipoActivo();
    nuevoId();
    cargarTabla();
    }
private void nuevoId() {
    txtId1.setText(negocio.siguienteId());
    txtNombre1.setText("");
    txtPeriodos1.setText("");
    txtValorCompra1.setText("");

    if (cmbTipoActivo1.getItemCount() > 0) {
        cmbTipoActivo1.setSelectedIndex(0);
    }

    txtNombre1.requestFocus();
}

private void cargarComboTipoActivo() {
    cmbTipoActivo1.removeAllItems();

    List<TipoActivo> lista = negocio.listarTiposActivo();

    if (lista != null) {
        for (TipoActivo t : lista) {
            cmbTipoActivo1.addItem(t.getCodigo() + " - " + t.getNombre());
        }
    }
}

private void cargarTabla() {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Periodos");
    modelo.addColumn("Valor compra");
    modelo.addColumn("Tipo activo");

    List<Activo> lista = negocio.listar();

    if (lista != null) {
        for (Activo a : lista) {
            String tipo = "";

            if (a.getCodTipo() != null) {
                tipo = a.getCodTipo().getNombre();
            }

            modelo.addRow(new Object[]{
                a.getId(),
                a.getNombre(),
                a.getPeriodosDepreciacion(),
                a.getValorCompra(),
                tipo
            });
        }
    }

    jTable2.setModel(modelo);
}

private boolean validarCampos() {
    if (txtNombre1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el nombre del activo");
        txtNombre1.requestFocus();
        return false;
    }

    if (txtPeriodos1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese los periodos de depreciación");
        txtPeriodos1.requestFocus();
        return false;
    }

    if (txtValorCompra1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el valor de compra");
        txtValorCompra1.requestFocus();
        return false;
    }

    if (cmbTipoActivo1.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Primero debe registrar un tipo de activo");
        return false;
    }

    try {
        Integer.parseInt(txtPeriodos1.getText().trim());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Los periodos deben ser un número entero");
        txtPeriodos1.requestFocus();
        return false;
    }

    try {
        new BigDecimal(txtValorCompra1.getText().trim());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "El valor de compra debe ser numérico");
        txtValorCompra1.requestFocus();
        return false;
    }

    return true;
}

private String obtenerCodigoTipoSeleccionado() {
    String texto = cmbTipoActivo1.getSelectedItem().toString();
    String codigo = texto.substring(0, texto.indexOf(" - "));
    return codigo;
}

private void seleccionarTipoActivo(String codigo) {
    for (int i = 0; i < cmbTipoActivo1.getItemCount(); i++) {
        String item = cmbTipoActivo1.getItemAt(i).toString();

        if (item.startsWith(codigo + " - ")) {
            cmbTipoActivo1.setSelectedIndex(i);
            return;
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        tblActivo = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtPeriodos1 = new javax.swing.JTextField();
        txtValorCompra1 = new javax.swing.JTextField();
        cmbTipoActivo1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Activos depreciables");

        btnInsertar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblActivoMouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        tblActivo.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Períodos de depreciación:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText(" Valor de compra:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Tipo de activo:");

        txtId1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });

        txtNombre1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        txtPeriodos1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPeriodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeriodos1ActionPerformed(evt);
            }
        });

        txtValorCompra1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtValorCompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCompra1ActionPerformed(evt);
            }
        });

        cmbTipoActivo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbTipoActivo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoActivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActivo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(95, 95, 95)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValorCompra1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(txtId1)
                            .addComponent(txtNombre1)
                            .addComponent(txtPeriodos1)
                            .addComponent(cmbTipoActivo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnInsertar)
                        .addGap(17, 17, 17)
                        .addComponent(btnModificar)
                        .addGap(7, 7, 7)
                        .addComponent(btnEliminar)
                        .addGap(25, 25, 25)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(tblActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPeriodos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValorCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbTipoActivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar))
                .addGap(36, 36, 36)
                .addComponent(tblActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
          if (!validarCampos()) {
        return;
    }

    String codTipo = obtenerCodigoTipoSeleccionado();

    int r = negocio.insertar(
            txtId1.getText(),
            txtNombre1.getText().trim(),
            Integer.parseInt(txtPeriodos1.getText().trim()),
            new BigDecimal(txtValorCompra1.getText().trim()),
            codTipo
    );

    if (r == 1) {
        JOptionPane.showMessageDialog(this, "Activo insertado correctamente");
        cargarTabla();
        nuevoId();
    } else {
        JOptionPane.showMessageDialog(this, "Error al insertar el activo");
    }
      
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         if (!validarCampos()) {
        return;
    }

    String codTipo = obtenerCodigoTipoSeleccionado();

    int r = negocio.modificar(
            txtId1.getText(),
            txtNombre1.getText().trim(),
            Integer.parseInt(txtPeriodos1.getText().trim()),
            new BigDecimal(txtValorCompra1.getText().trim()),
            codTipo
    );

    if (r == 1) {
        JOptionPane.showMessageDialog(this, "Activo modificado correctamente");
        cargarTabla();
        nuevoId();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo modificar el activo");
    }
       
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
          int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que desea eliminar este activo?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION
    );

    if (opcion == JOptionPane.YES_OPTION) {
        int r = negocio.eliminar(txtId1.getText());

        if (r == 1) {
            JOptionPane.showMessageDialog(this, "Activo eliminado correctamente");
            cargarTabla();
            nuevoId();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el activo");
        }
    }
    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       String id = JOptionPane.showInputDialog(this, "Ingrese el ID del activo:");

    if (id != null && !id.trim().isEmpty()) {
        Activo a = negocio.buscar(id.trim());

        if (a != null) {
            txtId1.setText(a.getId());
            txtNombre1.setText(a.getNombre());

            if (a.getPeriodosDepreciacion() != null) {
                txtPeriodos1.setText(a.getPeriodosDepreciacion().toString());
            } else {
                txtPeriodos1.setText("");
            }

            if (a.getValorCompra() != null) {
                txtValorCompra1.setText(a.getValorCompra().toString());
            } else {
                txtValorCompra1.setText("");
            }

            if (a.getCodTipo() != null) {
                seleccionarTipoActivo(a.getCodTipo().getCodigo());
            }

        } else {
            JOptionPane.showMessageDialog(this, "No existe el activo");
        }
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblActivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblActivoMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_tblActivoMouseClicked

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void txtPeriodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeriodos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeriodos1ActionPerformed

    private void txtValorCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCompra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCompra1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         int fila = jTable2.getSelectedRow();

    if (fila >= 0) {
        String id = jTable2.getValueAt(fila, 0).toString();

        Activo a = negocio.buscar(id);

        if (a != null) {
            txtId1.setText(a.getId());
            txtNombre1.setText(a.getNombre());

            if (a.getPeriodosDepreciacion() != null) {
                txtPeriodos1.setText(a.getPeriodosDepreciacion().toString());
            } else {
                txtPeriodos1.setText("");
            }

            if (a.getValorCompra() != null) {
                txtValorCompra1.setText(a.getValorCompra().toString());
            } else {
                txtValorCompra1.setText("");
            }

            if (a.getCodTipo() != null) {
                seleccionarTipoActivo(a.getCodTipo().getCodigo());
            }
        }
    }
    }//GEN-LAST:event_jTable2MouseClicked

    private void cmbTipoActivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActivo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActivo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoActivoDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoActivoDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoActivoDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoActivoDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoActivoDep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbTipoActivo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable jTable2;
    private javax.swing.JScrollPane tblActivo;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtPeriodos1;
    private javax.swing.JTextField txtValorCompra1;
    // End of variables declaration//GEN-END:variables
}
